<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Recent Posts</name>
   <tag></tag>
   <elementGuidId>dc31af3a-c8dc-49a7-b006-935dec860291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='recent-posts-2']/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.widget-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>ac9f38ea-c5cc-4c16-a19e-bd2221da6a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-title</value>
      <webElementGuid>eb4ae1b5-9d21-4896-b1ce-6cd67af71914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recent Posts</value>
      <webElementGuid>47b80be2-8519-4c50-96d9-b640692147f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recent-posts-2&quot;)/h2[@class=&quot;widget-title&quot;]</value>
      <webElementGuid>5c7de640-c074-4acf-9b64-74368e8b0170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='recent-posts-2']/h2</value>
      <webElementGuid>8e7304c7-3775-40a1-8b23-951d24f025d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::h2[1]</value>
      <webElementGuid>d0fbfa92-e802-49e7-af6f-413a29df2bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for:'])[1]/following::h2[1]</value>
      <webElementGuid>418439cd-12b2-4ff8-ba3c-06c55256d6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello world!'])[1]/preceding::h2[1]</value>
      <webElementGuid>fa6184be-3d92-4fb5-ad76-4690aaa76491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Comments'])[1]/preceding::h2[1]</value>
      <webElementGuid>ff9c76ee-8e3a-406a-9da6-f7d1795c61f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recent Posts']/parent::*</value>
      <webElementGuid>b0193502-15e8-4b0d-a67d-9e376a4c6791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/h2</value>
      <webElementGuid>37d11839-b8dd-4963-aaa7-108c99c383fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Recent Posts' or . = 'Recent Posts')]</value>
      <webElementGuid>6abcead5-e1a6-4a04-b689-3ad34eef9b19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
