<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>blockquote_Hi there Im a bike messenger by _996985</name>
   <tag></tag>
   <elementGuidId>6b857430-13b0-4812-839f-c2400ba7cfe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-2']/div/blockquote</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>blockquote.wp-block-quote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>blockquote</value>
      <webElementGuid>9fe198ef-1f5a-449b-9004-2754ed1342d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-quote</value>
      <webElementGuid>3b71018c-dbd4-49b0-b930-6e72fb424fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi there! I’m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like piña coladas. (And gettin’ caught in the rain.)</value>
      <webElementGuid>e5399664-47ad-483e-ac8e-cbb64126dea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-2&quot;)/div[@class=&quot;entry-content&quot;]/blockquote[@class=&quot;wp-block-quote&quot;]</value>
      <webElementGuid>718ae293-1932-4834-bc00-51c4670ca647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-2']/div/blockquote</value>
      <webElementGuid>6781032b-136b-45d8-b445-9839ca0c745b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample Page'])[2]/following::blockquote[1]</value>
      <webElementGuid>b280a8b7-8932-4538-82c4-482cbc9d111c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[1]/following::blockquote[1]</value>
      <webElementGuid>16615ccd-bac2-47b2-81b8-2de2c8b18eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='your dashboard'])[1]/preceding::blockquote[2]</value>
      <webElementGuid>57418e8a-bce0-4d05-a22c-520239328b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for:'])[1]/preceding::blockquote[2]</value>
      <webElementGuid>5e08174d-34c9-4674-aa07-717d612e1dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//blockquote</value>
      <webElementGuid>8408253e-dc54-4587-9ea0-5bc52a9b6204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//blockquote[(text() = 'Hi there! I’m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like piña coladas. (And gettin’ caught in the rain.)' or . = 'Hi there! I’m a bike messenger by day, aspiring actor by night, and this is my website. I live in Los Angeles, have a great dog named Jack, and I like piña coladas. (And gettin’ caught in the rain.)')]</value>
      <webElementGuid>a3b2fb0c-8079-4251-885f-180f349a7e11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
